### ISSUE TITLE
Script for Expanding Hard Drive

### ISSUE THREAD

**Issue by DexterInd** [DexterInd/Raspbian_For_Robots#10]
Need to be able to expand the size of the usable space to the size of the SD Card.  Possibly incorporate into GUI.

**Comment by dlech** [comment]
Here is what we use in ev3dev. We just run it on the first boot.

        # expand the root file system
        # Note, this will break if using an initramfs
        parted --script /dev/mmcblk0 unit % resizepart 2 100%
        partprobe
        resize2fs /dev/mmcblk0p2

**Comment by DexterInd** [comment]
Hey @dlech thank you.  Going to have a look and give it a shot!

**Comment by CleoQc** [comment]
No longer required with Jessie or Stretch
