### ISSUE TITLE
Backup Button

### ISSUE THREAD

**Issue by DexterInd** [DexterInd/Raspbian_For_Robots#12]
Need a way to backup the Pi and user content to a USB drive.

**Comment by DexterInd** [comment]
@karan259 just need to have the py and sb files added to the backup at this point.

**Comment by CleoQc** [comment]
It would be nice to back up any directory under /home/pi that are not there by default, as the tutorials tell people to create directories there.

**Comment by DexterInd** [comment]
This seems to be solved by @karan259 's work.
