### ISSUE TITLE
Raspbian Stretch update?

### ISSUE THREAD

**Issue by fhunleth** [DexterInd/Raspbian_For_Robots#169]
The current Raspbian release [2017-11-29/Stretch](https://www.raspberrypi.org/downloads/raspbian/) has performance improvements and a couple USB stability fixes that we'd really like to use. Are there plans to update Raspbian for Robots to this version?

**Comment by CleoQc** [comment]
Expect something really soon. :) Finally!

**Comment by RobertLucian** [comment]
I believe it's safe to say we now have a Stretch release for Raspbian For Robots.

**Comment by CleoQc** [comment]
It's been a few weeks :)
