### ISSUE TITLE
HTTP/HTTPS Connection

### ISSUE THREAD

**Issue by DexterInd** [DexterInd/Raspbian_For_Robots#20]
Need a way to force http, not https. The webpage fails if it goes to HTTPS.  Seeing that if you login to https://dex.local, a blank page appears.  Mozilla seems to sometimes want to force https.  Is there a way to force http protocol for the dex.local page?

Note we can't disable https because Terminal program uses it, needs it.

**Comment by DexterInd** [comment]
@BandonRandon you might also have an idea here?

**Comment by BandonRandon** [comment]
Just to make sure I'm clear on this and #19 the intended behaviour will be to:
1) Always redirect https://dex.local to http://dex.local except when running the terminal program 
2) Never cache the dex.local page locally within the browser.

**Comment by DexterInd** [comment]
That's right.  One other critical piece though is that we're serving up noVNC on port :8001 (this can be http) and terminal on :4200 (this should be https).

We're serving up on Apache so I'm not sure if that affects the best way to handle it?

**Comment by CleoQc** [comment]
I believe this has been solved, right?

**Comment by DexterInd** [comment]
Not exactly.  We solved the https issue with shell in a box, but I'm concerned about https with dex.local page.

**Comment by DexterInd** [comment]
Just to continue the conversation: I think from time to time that some customers when they login to http://dex.local are getting forced to https://dex.local  .  So a blank page shows up (since there's nothing at https://  location.

**Comment by CleoQc** [comment]
any idea why https is being forced onto them?

**Comment by DexterInd** [comment]
Not sure.  I really don't know, which is why I wanted to make sure that we forced http in the browser.

**Comment by DexterInd** [comment]
This seems to be solved.  Somehow.
