### ISSUE TITLE
GoPiGo binary causing issues with gpg

### ISSUE THREAD

**Issue by tangowhisky37** [DexterInd/Raspbian_For_Robots#46]
Folks,

Am not sure if you've had similar issues but while installing certain applications on the RaspPI which is also used for my GoPiGo i started seeing GPG (Gnu Privacy) errors. I also realized that for some reason the post installation scripts running on the Raspi would barf and fail with a GoPiGo message...

GoPiGo Found
Firmware version
Battery Voltage..

I think this is because we've named a binary as /usr/bin/gpg to provide the above. The issue is Debian also has a GPG binary with a similar name and all programs that need to use GPG seem to fail.

It's a minor issue. I've fixed it by renaming the binary to /usr/bin/GoPiGo but don't know what's the impact of doing that. The fix allows me to continue working with my other apps on the RasPi.

Thoughts?

Cheers,
Trevor

**Comment by CleoQc** [comment]
No impact at all in changing the name of it. Must have been surprising to see a GoPiGo message pop up!

**Comment by dlech** [comment]
Just a suggestion: it would be more "linuxy" to keep the file name all lower case, so `/usr/bin/gopigo`.

**Comment by tangowhisky37** [comment]
Thanks guys.

**Comment by CleoQc** [comment]
This has been fixed with this PR: https://github.com/DexterInd/GoPiGo/commit/25957625ec267a7dd83e7c602e2a19ab56f3f473
