### ISSUE TITLE
Remove change in rc.sh about Cinch update

### ISSUE THREAD

**Issue by CleoQc** [DexterInd/Raspbian_For_Robots#66]
@DexterInd  I talked to a teacher tonight, and she runs Cinch. Her class robots all have the same hostname, and just their SSID was changed for Cinch to be usable.
Having those lines in:
https://github.com/DexterInd/Raspbian_For_Robots/blob/master/upd_script/rc.sh#L21-L26
would mean all her robots would revert to 'dex' with no warning. 

Suggestion: postpone those changes until we can pass the word around that hostnames must also be unique, not just SSIDs.

**Comment by DexterInd** [comment]
Ok, @CleoQc I'm going to try to revert those changes.  Thanks!
