### ISSUE TITLE
Does Update reset the hostname back to dex.local?

### ISSUE THREAD

**Issue by DexterInd** [DexterInd/Raspbian_For_Robots#7]
@CleoQc asked if this resets the hostname.  Going to try to rename the hostname, update, and then see where this goes.

**Comment by DexterInd** [comment]
No, doesn't seem to rewrite the hostname.  I set a custom hostname, ran the update, rebooted, and the custom hostname was retained.

**Comment by CleoQc** [comment]
Great! Good news! Did you happen to notice the messages to the user stating the host name was being rewritten, during the update!  It was those messages that got me worried.

**Comment by DexterInd** [comment]
Should we put a new ticket in to solve that?

**Comment by CleoQc** [comment]
I'll probably be the only one to notice them, as I was paying close attention to the process. I think most people will start the update and walk away. Maybe just make a note of it somewhere and next time this is revisited, it could be looked at.
